spring:
  datasource:
    url: jdbc:h2:mem:meteo
    username: tiila
    password: tiila
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
  cloud:
    mvc:
      token-relay:
        enabled: false
  secrets:
    openweather:
      token: 2e1d20f5ff53590209221206b214a244